### ISSUE TITLE
Request flood in web browser

### ISSUE THREAD

**Issue by lidel** [libp2p/js-libp2p-delegated-content-routing#12]
## Problem

I've been testing delegated routing in browser context, namely with js-ipfs embedded in Brave (https://github.com/ipfs-shipyard/ipfs-companion/issues/716).

It produces pretty intense list of pending requests when browsing [/ipns/tr.wikipedia-on-ipfs.org](https://ipfs.io/ipns/tr.wikipedia-on-ipfs.org/wiki/Anasayfa.html) :carousel_horse:  :sweat_drops: 

> ![pending-swarm-connect-2019-07-12--22-35-50](https://user-images.githubusercontent.com/157609/61157793-6df28b00-a4f7-11e9-9e44-45b3ba26cba6.png)

> ![swarm-connect-content-routing-2019-07-12--22-38-42](https://user-images.githubusercontent.com/157609/61157848-94b0c180-a4f7-11e9-823c-1226ff7d3aaa.png)

Modern browsers limit the number of concurrent requests to **~6** per hostname.
Everything over the limit lands in "pending" state.

On some pages it takes a dozen of seconds for the browser to finish a pending list like the one above (it was multiple screens), and while it happens nothing else works.

When run in regular page, this flood of `swarm connect` results in slow browsing experience (nothing loads, "waiting for available socket" displayed in bottom left). 

In my case (Brave + [chrome.sockets](https://github.com/ipfs-shipyard/ipfs-companion/issues/664)), coupled with regular preload requests it produced more severe `net::ERR_INSUFFICIENT_RESOURCES`:

> ![net-insufficient-resources-2019-07-12--21-37-15](https://user-images.githubusercontent.com/157609/61157956-d477a900-a4f7-11e9-89fd-8ab939f7fd36.png)

## Fix 

My initial idea would be to limit the number of concurrent requests using something like [p-queue](https://github.com/sindresorhus/p-queue) around these lines:

https://github.com/libp2p/js-libp2p-delegated-content-routing/blob/69f1f94094231b87a27a9af4d34006614c6cdfe2/src/index.js#L90-L92

I'll prepare PR with this.

**Comment by lidel** [comment]
Note to self: 

- when we throttle the number of parallel requests [DoS protection gets triggered at public preload nodes](https://user-images.githubusercontent.com/157609/61639891-a3883880-ac9c-11e9-8dd4-fa0dee9719c8.png)
- we don't cache successful `swarm connect` - requests are sent over and over again, but there should be an expectation that connection is alive at least for 1minute

**Comment by lidel** [comment]
Update: throttling helps, but is not enough. Some requests can take a very long time and will suffocate request queue because they have no built-in timeout (namely `/api/v0/refs`). This also means we can't use `js-ipfs-http-client` because it does not support cancellations:  https://github.com/ipfs/js-ipfs-http-client/issues/694. 

For this very reason js-ipfs  does not use ipfs-http-client for preload calls to `/api/v0/refs`: instead it is using  manual `fetch` with `AbortController` ([code](https://github.com/ipfs/js-ipfs/blob/v0.37.0-rc.0/src/core/runtime/preload-browser.js))

We need to do the same, or use [js-ipfs-http-client-lite](https://github.com/ipfs-shipyard/js-ipfs-http-client-lite) (add missing commands if needed).

**Comment by alanshaw** [comment]
@lidel they are mostly calls to `swarm.connect` - I'm not sure they are even needed. See the conversation here: https://github.com/libp2p/js-libp2p-delegated-content-routing/issues/14#issuecomment-514127168

**Comment by lidel** [comment]
@alanshaw yeah, that confirms what I'm seeing:  `swarm connect` from delegate to js-ipfs always succeeds, no matter what multiaddr was used:

> ![2019-07-23--17-01-34](https://user-images.githubusercontent.com/157609/61724952-38f3fd00-ad6f-11e9-93b1-eef58722c946.png)
> ![2019-07-23--17-00-53](https://user-images.githubusercontent.com/157609/61724955-38f3fd00-ad6f-11e9-84f9-59935923c09e.png)


AFAIK autorelay feature is off on bootstrap nodes. This means  p2p-circuits are never used(!) and it works only because `node0.preload.ipfs.io` is reusing already existing connection that my node established with  because `node0` it ones of bootstrap nodes.

(go-ipfs ignores multiaddr if it already has a working connection with same peerId)

This means we could either remove `swarm connect` entirely (js-ipfs will maintain connection to delegate/bootstrap node, no need to force it), or finish early, after first success (decreasing number of requests from one per bootstrap, to a single one).

**Comment by jacobheun** [comment]
Catching up on this now, sorry for the delay.

> Given the docs explicitly state that delegate needs to also be a bootstrap node (libp2p/js-libp2p#371), I'd vote for removal of swarm connect call and relatec code.

Yes, we should remove this code. Right now we're telling the delegate to connect to us through every bootstrap as relays, which isn't going to work as they're not relays. I think this code may have made the assumption that we could be using a delegate that's not publicly dialable, which is wrong.

Getting the Priority Peer or (Friend Peer) functionality in place and documenting that users should have their delegate node as a priority peer should be sufficient for us just calling refs on the delegate.

All the bootstrap node stuff just needs to go away.

**Comment by lidel** [comment]
@jacobheun neat! I removed bootstrap node stuff in https://github.com/libp2p/js-libp2p-delegated-content-routing/pull/16/commits/7ea2eae3318ac3b7e602200c958507c447b7d14c (part of PR #16)
