### ISSUE TITLE
Cannot Browserify after 0.2.3

### ISSUE THREAD

**Issue by VandeurenGlenn** [libp2p/js-libp2p-delegated-content-routing#13]
Cannot find module 'babelify' from '...\node_modules\peer-id\node_modules\async'

**Comment by alanshaw** [comment]
Check out https://github.com/ipfs/js-ipfs/issues/2283#issuecomment-513696919 for info on this and a workaround.

**Comment by alanshaw** [comment]
This has now been resolved with the new version of `peer-id@0.12.4`
