### ISSUE TITLE
Missing request timeouts in web browser

### ISSUE THREAD

**Issue by lidel** [libp2p/js-libp2p-delegated-content-routing#15]
Throttling introduced in #12  helps with request flood, but there is a separate problem of the lack of request timeouts in web browser. Some requests can take a very long time and will suffocate request queue because they have no built-in timeout (namely `/api/v0/refs`):

![slow-6-refs-suffocating-pending-calls-2019-07-23--00-18-22](https://user-images.githubusercontent.com/157609/61669709-4a8ec380-ace1-11e9-8658-f65c2da0035a.png)

This also means we can't use `js-ipfs-http-client` because it does not support cancellations:  https://github.com/ipfs/js-ipfs-http-client/issues/694. For this very reason js-ipfs  does not use ipfs-http-client for preload calls to `/api/v0/refs`: instead it is using  manual `fetch` with `AbortController` in web browser ([`preload-browser.js`](https://github.com/ipfs/js-ipfs/blob/v0.37.0-rc.0/src/core/runtime/preload-browser.js)) and `req.abort` in Node ([`preload-nodejs.js`](https://github.com/ipfs/js-ipfs/blob/v0.37.0-rc.0/src/core/runtime/preload-nodejs.js))

We need to do the same, or use [js-ipfs-http-client-lite](https://github.com/ipfs-shipyard/js-ipfs-http-client-lite) (add missing commands if needed).

@jacobheun  @alanshaw thoughts on which way is better? Is this library aimed only at browsers, or will it be used in Node as well?

**Comment by alanshaw** [comment]
It'll be used in all environments.

If we call `provide` every CID we add (which [I think we do](https://github.com/ipfs/js-ipfs-bitswap/blob/2e4d69a3ea6befadae8fc4b12f915e7403f8278f/src/index.js#L150-L166)) then we don't need the `recursive` flag. This will reduce the RTT for each call to `provide` significantly.

**Comment by achingbrain** [comment]
This module has an internal request queue so this should be fixed now.
