### ISSUE TITLE
Add supported for Put/Get operations (IPNS in browsers etc)

### ISSUE THREAD

**Issue by aschmahmann** [libp2p/js-libp2p-delegated-content-routing#49]
We should add support for asking other nodes to do Put/Get operations for us (e.g. for IPNS records). This should basically be just adding support for an HTTP API call. 

cc @lidel https://github.com/ipfs/js-ipfs/issues/3722 https://github.com/ipfs/js-ipfs/issues/2921

**Comment by lidel** [comment]
Ack, if we have this + preload/delegate nodes using [accelerated-dht-client](https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features.md#accelerated-dht-client)  + https://github.com/ipfs/js-ipfs/issues/3722 we have IPNS (at resolution) working pretty well in browsers. 

Added to maintenance board.

**Comment by tinytb** [comment]
- will be done with delegated content routing http api: https://github.com/ipfs/specs/pull/337
- there will be a client for that api
- see https://github.com/ipfs/kubo/issues/9479

**Comment by achingbrain** [comment]
Fixed by #68
